#!/bin/bash

CC=$1

TIMESTAMP=$(date +%s)

if [[ -z $CC ]]; then
    echo "Usage:"
    echo "  ./cache-osm <Country>"
    echo ""
    echo "Download and extract the latest OSM PBF for a given country area"
    echo ""
    echo "Example"
    echo "./cache ca"
    exit
fi

set -euo pipefail

URL=$(jq -rc .$CC $(dirname $0)/cache-osm.conf)

if [[ $URL == "null" ]]; then
    echo
    echo "not ok - download location not found in config ./util/cache-osm.conf"
    echo
    exit 1
fi

curl $URL > /tmp/$CC.osm.pbf

osmium export \
    --output-format geojsonseq \
    /tmp/$CC.osm.pbf \
    | jq -rc '.properties.source = "osm"' \
    > /tmp/${CC}_unfiltered.geojsonld

cargo run -- filter \
    /tmp/${CC}_unfiltered.geojsonld \
    > $(dirname $0)/../${CC}.geojsonld

echo "ok - ./$CC.geojsonld"

