#!/bin/bash

CC=$1
export PGPASSWORD=$POSTGRES_PASSWORD

TIMESTAMP=$(date +%s)

if [[ -z $CC ]]; then
    echo "Usage:"
    echo "  ./cache-nasa <path>/*.asc"
    echo ""
    echo "Load .asc formatted NASA SEDAC data"
    echo ""
    echo "Example"
    echo "./cache-nasa ~/path-to-asc-foler/"
    exit
fi

set -euo pipefail

echo "
    CREATE SCHEMA IF NOT EXISTS pop;
" | psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB


# -I Create a spatial index for imported data
# -e Execute instructions individually instead of a transaction
# -s Set EPSG code
# -t Set tilesize
raster2pgsql \
    -I -e \
    -s 4326 \
    -t auto \
    $1/*.asc pop.population \
    | tee /tmp/raster.sql \
    | psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB

